### ISSUE TITLE
after $ sign ?

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/Introduction-RStudio-Git-GitHub#10]
Hi @tlestang 
you added '(after the $)' in the SSH file

In the command line, start the ssh-agent with (after the $):
`eval "$(ssh-agent -s)"`

I'm now confused what needs to be typed?
eval "ssh-agent-s"  ??
if then we could just remove the $?

https://github.com/MalikaIhle/Introduction-RStudio-Git-GitHub/blob/5c7ed30d1d1959dd05707385e8e2db5b383bad9b/SSH.md?plain=1#L123-L127

**Comment by tlestang** [comment]
Good catch, I reverted an old commit that contained this line.
What must be typed is 
```bash
eval "$(ssh-agent -s)"
```
```
`ssh-agent -s` itself returns a command.

**Comment by tlestang** [comment]
Removed the confusing reference to the dollar prompt ([71aaed1](https://github.com/MalikaIhle/Introduction-RStudio-Git-GitHub/commit/71aaed15fa2ea34c1ca2b37636c3bd0c45ba47b3))

**Comment by MalikaIhle** [comment]
thanks!!
